builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"

archives:
  - name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: git-open
    description: Opens your Git repository in your browser
    homepage: https://github.com/arbourd/git-open

    test: |
      system "git", "clone", "https://github.com/arbourd/git-open.git"

      cd "git-open" do
        assert_match "Opening https://github.com/arbourd/git-open",
                    shell_output("#{bin}/git-open")
        assert_match "Opening https://github.com/arbourd/git-open/tree/main/LICENSE",
                    shell_output("#{bin}/git-open LICENSE")
        assert_match "Opening https://github.com/arbourd/git-open/commit/71e081deeb92764e1bae203419ac72de1d935d2f",
                    shell_output("#{bin}/git-open 71e081deeb92764e1bae203419ac72de1d935d2f")
      end

    conflicts:
      - git-open

    directory: Formula

    repository:
      owner: arbourd
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    commit_author:
      name: Dylan Arbour
      email: arbourd@users.noreply.github.com
